trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'NativeImport/**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'NativeImport/**/*.csproj'
    versioningScheme: 'off'