namespace libplctag
{
    public enum Status
    {
        Pending = 1,
        Ok = 0,
        ErrorAbort = -1,
        ErrorBadConfig = -2,
        ErrorBadConnection = -3,
        ErrorBadData = -4,
        ErrorBadDevice = -5,
        ErrorBadGateway = -6,
        ErrorBadParam = -7,
        ErrorBadReply = -8,
        ErrorBadStatus = -9,
        ErrorClose = -10,
        ErrorCreate = -11,
        ErrorDuplicate = -12,
        ErrorEncode = -13,
        ErrorMutexDestroy = -14,
        ErrorMutexInit = -15,
        ErrorMutexLock = -16,
        ErrorMutexUnlock = -17,
        ErrorNotAllowed = -18,
        ErrorNotFound = -19,
        ErrorNotImplemented = -20,
        ErrorNoData = -21,
        ErrorNoMatch = -22,
        ErrorNoMem = -23,
        ErrorNoResources = -24,
        ErrorNullPtr = -25,
        ErrorOpen = -26,
        ErrorOutOfBounds = -27,
        ErrorRead = -28,
        ErrorRemoteErr = -29,
        ErrorThreadCreate = -30,
        ErrorThreadJoin = -31,
        ErrorTimeout = -32,
        ErrorTooLarge = -33,
        ErrorTooSmall = -34,
        ErrorUnsupported = -35,
        ErrorWinsock = -36,
        ErrorWrite = -37,
        ErrorPartial = -38,
        ErrorBusy = -39
    }
}