namespace libplctag
{
    public enum StatusCodes
    {
        STATUS_PENDING = 1,
        STATUS_OK = 0,
        ERROR_ABORT = -1,
        ERROR_BAD_CONFIG = -2,
        ERROR_BAD_CONNECTION = -3,
        ERROR_BAD_DATA = -4,
        ERROR_BAD_DEVICE = -5,
        ERROR_BAD_GATEWAY = -6,
        ERROR_BAD_PARAM = -7,
        ERROR_BAD_REPLY = -8,
        ERROR_BAD_STATUS = -9,
        ERROR_CLOSE = -10,
        ERROR_CREATE = -11,
        ERROR_DUPLICATE = -12,
        ERROR_ENCODE = -13,
        ERROR_MUTEX_DESTROY = -14,
        ERROR_MUTEX_INIT = -15,
        ERROR_MUTEX_LOCK = -16,
        ERROR_MUTEX_UNLOCK = -17,
        ERROR_NOT_ALLOWED = -18,
        ERROR_NOT_FOUND = -19,
        ERROR_NOT_IMPLEMENTED = -20,
        ERROR_NO_DATA = -21,
        ERROR_NO_MATCH = -22,
        ERROR_NO_MEM = -23,
        ERROR_NO_RESOURCES = -24,
        ERROR_NULL_PTR = -25,
        ERROR_OPEN = -26,
        ERROR_OUT_OF_BOUNDS = -27,
        ERROR_READ = -28,
        ERROR_REMOTE_ERR = -29,
        ERROR_THREAD_CREATE = -30,
        ERROR_THREAD_JOIN = -31,
        ERROR_TIMEOUT = -32,
        ERROR_TOO_LARGE = -33,
        ERROR_TOO_SMALL = -34,
        ERROR_UNSUPPORTED = -35,
        ERROR_WINSOCK = -36,
        ERROR_WRITE = -37
    }
}