name: Build and publish libplctag.NET nuget package

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true 
    
    - name: Publish libplctag on version change
      run: .\build.cmd ReleaseLibplctag --nuget-api-key ${{secrets.NUGET_API_KEY}}
      
    - name: Publish libplctag.NativeImport on version change
      run: .\build.cmd ReleaseLibplctagNativeImport --nuget-api-key ${{secrets.NUGET_API_KEY}}
