name: Build and publish libplctag.NET nuget package

on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true 
    
    - name: Publish all packages on version change
      run: .\build.cmd ReleaseAll --nuget-api-key ${{secrets.NUGET_API_KEY}}
