name: Test libplctag.NativeImport

on: [workflow_dispatch,push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true 
    
    - name: Build all and run tests
      run: .\build.cmd TestLibplctagNativeImport
