name: Test libplctag

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true 
    
    - name: Build all and run tests
      run: ./build.sh TestLibplctag
