name: Update core binaries

on:

  workflow_dispatch:
    inputs:
      libplctag_core_version:
        required: true
        description: Version of libplctag core to download (e.g. 2.5.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Pull in latest libplctag core binaries into repository
        run: ./build.sh UpdateCoreBinaries --libplctag-core-version ${{ github.event.inputs.libplctag_core_version }}
        
